// Generated by FlutterFlow. The stateful in-memory store backing the mock
// backend. Data lives for the duration of the app session and is re-seeded
// on restart or via MockDataStore.instance.reset().

import 'dart:convert';
import 'dart:math';

import 'mock_seed_data.dart';

/// How ids are generated for rows created at runtime.
enum MockIdStrategy { autoIncrementInt, uuid }

/// Static configuration of a mock dataset, generated from the project's mock
/// backend configuration.
class MockDatasetConfig {
  const MockDatasetConfig({
    required this.idFieldName,
    required this.idStrategy,
    required this.seedRowsJson,
  });

  final String idFieldName;
  final MockIdStrategy idStrategy;

  /// The seed rows as a JSON array of objects.
  final String seedRowsJson;
}

/// A single ordering term of a [MockQuery].
class MockOrderBy {
  const MockOrderBy(this.fieldName, {this.descending = false});

  final String fieldName;
  final bool descending;
}

/// A backend-agnostic query against a mock dataset. Adapters translate their
/// surface's inputs (e.g. API endpoint variables) into this shape.
class MockQuery {
  const MockQuery({
    this.equals = const {},
    this.orderBy = const [],
    this.limit,
    this.offset,
  });

  /// Equality predicates, keyed by row field name.
  final Map<String, dynamic> equals;
  final List<MockOrderBy> orderBy;
  final int? limit;
  final int? offset;
}

class MockDataStore {
  MockDataStore._();

  static final MockDataStore instance = MockDataStore._();

  final Map<String, List<Map<String, dynamic>>> _tables = {};
  final Map<String, int> _nextIntId = {};
  final Random _random = Random();
  bool _seeded = false;

  /// Seeds all datasets from [MockSeedData] if not already seeded.
  void ensureSeeded() {
    if (_seeded) {
      return;
    }
    _seeded = true;
    MockSeedData.datasets.forEach((datasetKey, config) {
      final rows = _decodeSeedRows(config.seedRowsJson);
      _tables[datasetKey] = rows;
      _nextIntId[datasetKey] = _maxIntId(rows, config.idFieldName) + 1;
    });
  }

  /// Clears all runtime changes and re-seeds the store.
  void reset() {
    _tables.clear();
    _nextIntId.clear();
    _seeded = false;
    ensureSeeded();
  }

  /// Returns the rows of [datasetKey] matching [query], ordered and paginated.
  List<Map<String, dynamic>> list(
    String datasetKey, [
    MockQuery query = const MockQuery(),
  ]) {
    ensureSeeded();
    var rows = _table(datasetKey)
        .where((row) => _matchesEquals(row, query.equals))
        .toList();
    if (query.orderBy.isNotEmpty) {
      rows.sort((a, b) => _compareRows(a, b, query.orderBy));
    }
    final offset = query.offset ?? 0;
    if (offset > 0) {
      rows = rows.skip(offset).toList();
    }
    final limit = query.limit;
    if (limit != null && limit >= 0) {
      rows = rows.take(limit).toList();
    }
    return rows.map(_copyRow).toList();
  }

  /// The number of rows of [datasetKey] matching [query]'s equality
  /// predicates, ignoring pagination.
  int count(String datasetKey, [MockQuery query = const MockQuery()]) {
    ensureSeeded();
    return _table(
      datasetKey,
    ).where((row) => _matchesEquals(row, query.equals)).length;
  }

  /// Returns the row of [datasetKey] whose id equals [id], or null.
  Map<String, dynamic>? getById(String datasetKey, dynamic id) {
    ensureSeeded();
    final row = _findById(datasetKey, id);
    return row == null ? null : _copyRow(row);
  }

  /// Inserts [row] into [datasetKey], generating an id if the row does not
  /// already carry one, and returns the created row.
  Map<String, dynamic> create(String datasetKey, Map<String, dynamic> row) {
    ensureSeeded();
    final idField = _idField(datasetKey);
    final newRow = Map<String, dynamic>.from(row);
    if (newRow[idField] == null) {
      newRow[idField] = _generateId(datasetKey);
    } else {
      _accommodateExistingId(datasetKey, newRow[idField]);
    }
    _table(datasetKey).add(newRow);
    return _copyRow(newRow);
  }

  /// Merges [patch] into the row of [datasetKey] whose id equals [id]
  /// (PATCH semantics) and returns the updated row, or null if not found.
  Map<String, dynamic>? update(
    String datasetKey,
    dynamic id,
    Map<String, dynamic> patch,
  ) {
    ensureSeeded();
    final row = _findById(datasetKey, id);
    if (row == null) {
      return null;
    }
    patch.forEach((field, value) {
      // Never let a patch overwrite the row's id.
      if (field != _idField(datasetKey)) {
        row[field] = value;
      }
    });
    return _copyRow(row);
  }

  /// Deletes the row of [datasetKey] whose id equals [id]. Returns whether a
  /// row was deleted.
  bool delete(String datasetKey, dynamic id) {
    ensureSeeded();
    final table = _table(datasetKey);
    final initialLength = table.length;
    table.removeWhere(
      (row) => _valuesEqual(row[_idField(datasetKey)], id),
    );
    return table.length < initialLength;
  }

  List<Map<String, dynamic>> _table(String datasetKey) =>
      _tables.putIfAbsent(datasetKey, () => []);

  String _idField(String datasetKey) {
    final idField = MockSeedData.datasets[datasetKey]?.idFieldName;
    return (idField == null || idField.isEmpty) ? 'id' : idField;
  }

  Map<String, dynamic>? _findById(String datasetKey, dynamic id) {
    final idField = _idField(datasetKey);
    for (final row in _table(datasetKey)) {
      if (_valuesEqual(row[idField], id)) {
        return row;
      }
    }
    return null;
  }

  dynamic _generateId(String datasetKey) {
    final strategy = MockSeedData.datasets[datasetKey]?.idStrategy ??
        MockIdStrategy.autoIncrementInt;
    switch (strategy) {
      case MockIdStrategy.uuid:
        return _uuid();
      case MockIdStrategy.autoIncrementInt:
        final id = _nextIntId[datasetKey] ?? 1;
        _nextIntId[datasetKey] = id + 1;
        return id;
    }
  }

  /// Keeps the auto-increment counter ahead of explicitly provided int ids.
  void _accommodateExistingId(String datasetKey, dynamic id) {
    final intId = id is int ? id : int.tryParse(id.toString());
    if (intId != null && intId >= (_nextIntId[datasetKey] ?? 1)) {
      _nextIntId[datasetKey] = intId + 1;
    }
  }

  static List<Map<String, dynamic>> _decodeSeedRows(String seedRowsJson) {
    if (seedRowsJson.isEmpty) {
      return [];
    }
    try {
      final decoded = jsonDecode(seedRowsJson);
      if (decoded is! List) {
        return [];
      }
      return decoded
          .whereType<Map>()
          .map((row) => Map<String, dynamic>.from(row))
          .toList();
    } catch (_) {
      return [];
    }
  }

  static int _maxIntId(List<Map<String, dynamic>> rows, String idField) {
    var maxId = 0;
    for (final row in rows) {
      final value = row[idField];
      final intId = value is int ? value : int.tryParse('${value ?? ''}');
      if (intId != null && intId > maxId) {
        maxId = intId;
      }
    }
    return maxId;
  }

  static Map<String, dynamic> _copyRow(Map<String, dynamic> row) =>
      Map<String, dynamic>.from(row);

  static bool _matchesEquals(
    Map<String, dynamic> row,
    Map<String, dynamic> equals,
  ) =>
      equals.entries
          .every((entry) => _valuesEqual(row[entry.key], entry.value));

  /// Lenient equality: values coming from URLs or form inputs are often
  /// strings while seed rows hold typed values.
  static bool _valuesEqual(dynamic a, dynamic b) {
    if (a == b) {
      return true;
    }
    if (a == null || b == null) {
      return false;
    }
    return a.toString() == b.toString();
  }

  static int _compareRows(
    Map<String, dynamic> a,
    Map<String, dynamic> b,
    List<MockOrderBy> orderBy,
  ) {
    for (final term in orderBy) {
      final result = _compareValues(a[term.fieldName], b[term.fieldName]);
      if (result != 0) {
        return term.descending ? -result : result;
      }
    }
    return 0;
  }

  static int _compareValues(dynamic a, dynamic b) {
    if (a == null && b == null) {
      return 0;
    }
    // Nulls sort last.
    if (a == null) {
      return 1;
    }
    if (b == null) {
      return -1;
    }
    if (a is num && b is num) {
      return a.compareTo(b);
    }
    if (a is Comparable && b is Comparable && a.runtimeType == b.runtimeType) {
      return a.compareTo(b);
    }
    return a.toString().compareTo(b.toString());
  }

  String _uuid() {
    final bytes = List<int>.generate(16, (_) => _random.nextInt(256));
    // RFC 4122 version 4.
    bytes[6] = (bytes[6] & 0x0f) | 0x40;
    bytes[8] = (bytes[8] & 0x3f) | 0x80;
    final hex = bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();
    return '${hex.substring(0, 8)}-${hex.substring(8, 12)}-'
        '${hex.substring(12, 16)}-${hex.substring(16, 20)}-'
        '${hex.substring(20)}';
  }
}
