// Generated by FlutterFlow. Seed data and per-dataset configuration for the
// mock data store.

import 'mock_data_store.dart';

abstract class MockSeedData {
  /// Dataset configurations keyed by dataset key.
  static const Map<String, MockDatasetConfig> datasets = {};
}
