// Generated by FlutterFlow. In-app Test Mode debug control for the built-in
// mock backend: switch between the live backend and the mock backend at
// runtime, and reset mock data back to its seed state.
//
// This file is part of the backend-agnostic mock core and reasons only in
// terms of FFDataSourceMode and the mock data store re-seed operation.

import 'package:flutter/material.dart';

import 'ff_data_source.dart';

/// Wraps [child] and floats a collapsible mock backend debug control on top.
///
/// Mounted from the generated app's `MaterialApp.builder` only when the mock
/// backend is generated into the build, so release builds without the feature
/// are unaffected.
class MockDebugOverlay extends StatelessWidget {
  const MockDebugOverlay({super.key, required this.child});

  final Widget child;

  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: Directionality.maybeOf(context) ?? TextDirection.ltr,
      child: Stack(
        children: [
          child,
          const Positioned(
            right: 12,
            bottom: 12,
            child: SafeArea(child: _MockDebugPanel()),
          ),
        ],
      ),
    );
  }
}

class _MockDebugPanel extends StatefulWidget {
  const _MockDebugPanel();

  @override
  State<_MockDebugPanel> createState() => _MockDebugPanelState();
}

class _MockDebugPanelState extends State<_MockDebugPanel> {
  bool _expanded = false;

  @override
  Widget build(BuildContext context) {
    return Material(
      color: Colors.transparent,
      child: _expanded ? _buildExpanded(context) : _buildCollapsed(),
    );
  }

  Widget _buildCollapsed() {
    return ValueListenableBuilder<FFDataSourceMode>(
      valueListenable: FFDataSource.modeNotifier,
      builder: (context, mode, _) {
        final isMock = mode == FFDataSourceMode.mock;
        // No Tooltip here: this widget sits above the Navigator (router
        // builder), where no Overlay ancestor exists for tooltips.
        return InkWell(
          borderRadius: BorderRadius.circular(24),
          onTap: () => setState(() => _expanded = true),
          child: Container(
            width: 48,
            height: 48,
            decoration: BoxDecoration(
              color: isMock ? const Color(0xFF6C5CE7) : const Color(0xFF2D3436),
              shape: BoxShape.circle,
              boxShadow: const [
                BoxShadow(
                  color: Color(0x40000000),
                  blurRadius: 8,
                  offset: Offset(0, 2),
                ),
              ],
            ),
            child: const Icon(
              Icons.science_outlined,
              color: Colors.white,
              size: 22,
            ),
          ),
        );
      },
    );
  }

  Widget _buildExpanded(BuildContext context) {
    return Container(
      width: 260,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFF1E1E1E),
        borderRadius: BorderRadius.circular(12),
        boxShadow: const [
          BoxShadow(
            color: Color(0x40000000),
            blurRadius: 12,
            offset: Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(
                Icons.science_outlined,
                color: Colors.white,
                size: 18,
              ),
              const SizedBox(width: 8),
              const Expanded(
                child: Text(
                  'API Mocks',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              InkWell(
                borderRadius: BorderRadius.circular(16),
                onTap: () => setState(() => _expanded = false),
                child: const Padding(
                  padding: EdgeInsets.all(4),
                  child: Icon(Icons.close, color: Colors.white70, size: 18),
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          ValueListenableBuilder<FFDataSourceMode>(
            valueListenable: FFDataSource.modeNotifier,
            builder: (context, mode, _) {
              final isMock = mode == FFDataSourceMode.mock;
              return Row(
                children: [
                  Expanded(
                    child: Text(
                      isMock ? 'API calls: mock data' : 'API calls: live',
                      style: const TextStyle(
                        color: Colors.white70,
                        fontSize: 12,
                      ),
                    ),
                  ),
                  Text(
                    'Live',
                    style: TextStyle(
                      color: isMock ? Colors.white38 : Colors.white,
                      fontSize: 12,
                      fontWeight: isMock ? FontWeight.w400 : FontWeight.w600,
                    ),
                  ),
                  Switch(
                    value: isMock,
                    activeThumbColor: const Color(0xFF6C5CE7),
                    onChanged: (value) => FFDataSource.setMode(
                      value ? FFDataSourceMode.mock : FFDataSourceMode.live,
                    ),
                  ),
                  Text(
                    'Mock',
                    style: TextStyle(
                      color: isMock ? Colors.white : Colors.white38,
                      fontSize: 12,
                      fontWeight: isMock ? FontWeight.w600 : FontWeight.w400,
                    ),
                  ),
                ],
              );
            },
          ),
          const SizedBox(height: 8),
          const Text(
            'Switching takes effect on the next API call. Open screens may '
            'keep their current data until rebuilt.',
            style: TextStyle(color: Colors.white38, fontSize: 11),
          ),
          const SizedBox(height: 12),
          SizedBox(
            width: double.infinity,
            child: OutlinedButton.icon(
              onPressed: () => _confirmReset(context),
              style: OutlinedButton.styleFrom(
                foregroundColor: const Color(0xFFFF7675),
                side: const BorderSide(color: Color(0xFFFF7675)),
                padding: const EdgeInsets.symmetric(vertical: 10),
              ),
              icon: const Icon(Icons.restart_alt, size: 18),
              label: const Text('Reset mock API data'),
            ),
          ),
        ],
      ),
    );
  }

  Future<void> _confirmReset(BuildContext context) async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (dialogContext) => AlertDialog(
        title: const Text('Reset mock API data?'),
        content: const Text(
          'This discards all runtime changes and restores the mock API data '
          'to its seed state. This cannot be undone.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(dialogContext).pop(false),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () => Navigator.of(dialogContext).pop(true),
            style: TextButton.styleFrom(
              foregroundColor: const Color(0xFFD63031),
            ),
            child: const Text('Reset'),
          ),
        ],
      ),
    );
    if (confirmed != true) {
      return;
    }
    FFDataSource.resetMockData();
    if (!context.mounted) {
      return;
    }
    ScaffoldMessenger.maybeOf(context)?.showSnackBar(
      const SnackBar(content: Text('Mock API data reset to seed state.')),
    );
  }
}
